### ISSUE TITLE
Wifi not fixed

### ISSUE THREAD

**Issue by YMZnew** [eGust/Intel-10th-gen-NUC-Hackintosh#1]
I have installed opencore 0.63 on my nuc10 i7 .
now everything is fine except wifi . would you please guide me for the instruction to fix it ?
i couldnt understand the solution in your Readme.
thank you

**Comment by YMZnew** [comment]
I have removed itlwmx file from my bootloader and replace it with itlwm file from repository you mentioned. 
then reboot but not working yet

**Comment by eGust** [comment]
What you need to do is just open the file inside that folder with any text editor, search for specific text then replace it. That's already the most straightforward way I can explain it.
